name: RssCheckPush

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: 0 0/6 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.10.6
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run
        env:
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: python main.py
